name: Auto-Release Action
run-name: Automatically create the release

on:
  push:
    branches: ["main"]

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout codebase
      - name: Checkout codebase
        id: checkout
        uses: actions/checkout@v4

      # Create the release
      - name: Create release
        id: create-release
        uses: jrm402/auto-create-release-action@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
